config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :users, only: [:show]

  get 'homes/about'

  resources :words
end

app/models/word.rb
class Word < ApplicationRecord

  # association
  belongs_to :user

  # tag function
  acts_as_taggable
  acts_as_taggable_on :tags

  # validate
  validates :title, presence: true, length: { in: 1..20 }
  validates :word, presence: true, length: { in: 1..500 }
  validates :source, length: { maximum: 500 }
  validates :comment, length: { maximum: 10000 }

  # using carrierwave
  mount_uploader :picture, ImageUploader


end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit,:update,:destroy]

  def new
    @word = Word.new
  end

  def create
    @word = current_user.words.build(word_params)
    if @word.save
      ContactMailer.contact_mail(@word).deliver
      redirect_to words_path, notice: "新しい言葉を登録しました"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @word.destroy
    redirect_to words_path, notice:"登録されていた言葉を削除しました"
  end

  def update
    if @word.update(word_params)
      redirect_to words_path, notice: "登録されていた言葉を更新しました"
    else
      render 'edit'
    end
  end


  private
  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(
      :title,
      :word,
      :source,
      :comment,
      :picture,
      :picture_cache,
      :remove_picture,
      :tag_list,
    )
  end

  # ログインユーザのみ投稿の編集・削除許可
  def ensure_correct_user
    if current_user.id != @word.user_id
      redirect_to words_path, notice: "権限がありません"
    end
  end


end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <%= link_to tag, words_path(tag_name: tag) %>
<% end %>

app/views/words/edit.html.erb
<div class="container">
  <h1 class="mt-4 mb-3">言葉の編集</h1>
    <%= form_with(model: @word, local: true) do |form| %>
      <% if @word.errors.any? %>
       <div id="error_explanation">
         <h2><%= @word.errors.count %>件のエラーがあります。</h2>
         <ul>
         <% @word.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
      <% end %>
      <div class="row">
        <div class="col-lg-8 mb-4">
            <div class="control-group form-group">
              <div class="controls">
                <%= form.label :title %>
                <%= form.text_field :title, placeholder: "心に響いた言葉にタイトルをつけましょう", class:"form-control", id:"title" %>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= form.label :word %>
                <%= form.text_area :word, placeholder: "心に響いた言葉を記入してください",rows:"10", cols:"100", class:"form-control", id:"word", style:"resize:none" %>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= form.label :source %>
                <%= form.text_field :source, placeholder: "言葉のソースを入力しましょう(例:発言者・本のタイトル・ネットのURLなど)", class:"form-control", id:"source" %>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= form.label :comment %>
                <%= form.text_area :comment, placeholder: "言葉に対するあなたの思い・考えを入力しましょう", rows:"10", cols:"100", class:"form-control", id:"comment", style:"resize:none" %>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <%= form.label :emotion_list, "タグ" %>※カンマ区切りで複数のタグを登録出来ます。
                <%= text_field_tag 'word[tag_list]', @word.tag_list.join(','), class:"form-control", id:"tag", placeholder: "言葉に関する感情・考えなどを表すタグを付けましょう" %>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
              <%= form.label :picture %><br>
              <%= form.file_field :picture, id: :word_image %>
              <%= image_tag(@word.picture.url, size: "500x200") if @word.picture && @word.picture.url%>
              <%= form.hidden_field :picture_cache %><br>
              <label><%= form.check_box :remove_picture %> 画像を削除</label>
            </div>
          </div>

            <div class="actions">
              <%= form.submit class:"btn btn-primary", id:"sendMessageButton"%><br><br>
            </div>
              <%= link_to '一覧画面に戻る', words_path,class:"btn btn-primary", id:"sendMessageButton" %>
              <%= link_to 'この言葉の詳細画面へ', @word,class:"btn btn-primary", id:"sendMessageButton" %><br><br><br>
              <%= link_to 'この言葉を削除する', word_path(@word.id), method: :delete ,data: { confirm: '本当にこの言葉を削除してよろしいですか？' },class:"btn btn-secondary", id:"sendMessageButton" %>
    <% end %>
    </div>
  </div>
</div>

app/views/words/index.html.erb
<!-- Page Content -->
<div class="container">
  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3">投稿した言葉一覧</h1>

    <tr>
      <th><%= sort_link(@search, :title, "◇タイトルを五十音順で並び替え", default_order: :desc) %></th>
      <th><%= sort_link(@search, :word, "◇言葉を五十音順で並び替え", default_order: :desc) %></th>
      <th><%= sort_link(@search, :created_at, "◇投稿日で並び替え", default_order: :desc) %></th>
      <th><%= link_to '◇検索結果をクリア', words_path %><th>
    </tr>

   <tbody>
    <% @search_words.each do |word| %>

    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
              <% if word.picture? %>
                <%= image_tag word.picture.url, class:"img-fluid rounded" %>
              <% else %>
                <%= image_tag("http://placehold.it/750x300", class:"img-fluid rounded") %>
              <% end %>
          </div>
          <div class="col-lg-6">
            <h2 class="card-text"><%= word.word %></h2>
            <p class="card-title"><%= word.title %></p>
            <br>
            タグ：
            <%= render 'words/tag_list', tag_list: word.tag_list %>
            <br>
            <br>
            <%= link_to '詳細を見る', word_path(word.id), class:"btn btn-primary" %>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">
        <%= word.created_at.strftime("%Y年%m月%d日") %>　by <%= link_to word.user.name, user_path(word.user.id) %>
      </div>
    </div>
    <% end %>

 <br>


<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
  <li class="page-item">
      <%= paginate @search_words, class:"page-link" %>
  </li>
</ul>

</div>
<!-- /.container -->

app/views/words/new.html.erb
<div class="container">
  <h1 class="mt-4 mb-3">言葉の投稿</h1>
    <%= form_with(model: Word.new, local: true) do |form| %>

      <% if @word.errors.any? %>
       <div id="error_explanation">
         <h2><%= @word.errors.count %>件のエラーがあります。</h2>
         <ul>
         <% @word.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
      <% end %>
      <div class="row">
        <div class="col-lg-8 mb-4">
          <div class="control-group form-group">
            <div class="controls">
              <%= form.label :word %>
              <%= form.text_area :word, placeholder: "心に響いた言葉を記入してください",rows:"10", cols:"100", class:"form-control", id:"new_word", style:"resize:none" %>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <%= form.label :title %>
              <%= form.text_field :title, placeholder: "心に響いた言葉にタイトルをつけましょう", class:"form-control", id:"new_title" %>
            </div>
          </div>
          <div class="actions">
            <%= form.submit class:"btn btn-primary", id:"sendMessageButton"%><br><br>
          </div>
            <%= link_to '一覧画面に戻る', words_path,class:"btn btn-secondary", id:"sendMessageButton" %>
    <% end %>
    </div>
  </div>
</div>

app/views/words/show.html.erb
<div class="container">
  <h1 class="mt-4 mb-3">言葉の詳細</h1>
      <p>タイトル: <%= @word.title %></p>
      <p>言葉: <%= @word.word %></p>
      <p>ソース: <%= @word.source %></p>
      <p>自身のコメント: <%= @word.comment %></p>
      <p>投稿日: <%= @word.created_at.strftime("%Y年%m月%d日") %></p>
      <p>更新日: <%= @word.updated_at.strftime("%Y年%m月%d日") %></p>
      <p>作成者: <%= link_to @word.user.name, user_path(@word.user.id) %></p>
      <p>タグ: <%= render 'words/tag_list', tag_list: @word.tag_list %></p>
      <% if @word.picture? %>
      <p>画像:</p>
        <%= image_tag @word.picture.url, size: "500x200" %><br><br>
      <% end %>
       <br>
       <%= link_to '言葉の一覧画面へ', words_path, class:"btn btn-primary" %>
       <% if @word.user_id == current_user.id %>
       <%= link_to "言葉を編集する", edit_word_path(@word), class:"btn btn-primary" %><br><br><br>
       <%= link_to 'この言葉を削除する', word_path(@word.id), method: :delete ,data: { confirm: '本当にこの言葉を削除してよろしいですか？' },class:"btn btn-secondary", id:"sendMessageButton" %>
       <% end %>
 </div>