config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :users, only: [:show]

  get 'homes/about'

  resources :words
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CASIOPEA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
            <% if user_signed_in? %>
            <div class="container">
              <%= link_to "CASIOPEA", homes_about_path, class: "navbar-brand" %>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">

            <dl class="searchbox">
              <%= search_form_for @search, url: words_path do |f| %>
                <dt><%= f.text_field :title_or_word_cont, placeholder: '検索するテキストを入力', id:"title_or_word_search" %></dt>
                <dd><%= f.submit ("言葉で検索") , class: 'search-btn'%></dd>
              <% end %>
            </dl>

            <dl class="searchbox">
              <%= search_form_for @search, url: words_path do |f| %>
                <dt><%= f.text_field :tags_name_cont,placeholder: '検索するタグを入力' %></dt>
                <%= f.hidden_field :search, value: 'true' %>
                <dd><%= f.submit ("タグで検索") , class: 'search-btn'%></dd>
              <% end %>
            </dl>

              <li class="nav-item">
                <%= link_to "プロフィール", user_path(current_user.id), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", words_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "言葉の投稿", new_word_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>

            <% else %>

          <div class="container">
            <%= link_to "CASIOPEA", root_path, class: "navbar-brand" %>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "about", homes_about_path, class: "nav-link" %>
              </li>
                <li class="nav-item">
                  <%= link_to "サインアップ", new_user_registration_path, class: "nav-link" %>
                </li>
                  <li class="nav-item">
                  <%= link_to "ログイン", user_session_path, class: "nav-link" %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <br>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  </div >

    <%= yield %>

  </body>

</html>